sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_EMAIL_ADDRESS}

notification:
  email:
    provider: sendgrid

spring:
  jpa:
   show-sql: false
  ai:
   vertex:
    ai:
     gemini:
       chat:
        options:
          model: gemini-2.5-flash-lite
          temperature: 0.2